export let allRoleInfo = {
  Jean: { key: "Jean", name: "琴", attr: "feng", sexType: "woman", star: 5 },
  Lisa: { key: "Lisa", name: "丽莎", attr: "lei", sexType: "woman", star: 4 },
  Rosaria: {
    key: "Rosaria",
    name: "罗莎莉亚",
    attr: "bing",
    sexType: "woman",
    star: 4,
  },
  Eula: { key: "Eula", name: "优菈", attr: "bing", sexType: "woman", star: 5 },
  Ningguang: {
    key: "Ningguang",
    name: "凝光",
    attr: "yan",
    sexType: "woman",
    star: 4,
  },
  Beidou: {
    key: "Beidou",
    name: "北斗",
    attr: "lei",
    sexType: "woman",
    star: 4,
  },
  Shenhe: {
    key: "Shenhe",
    name: "申鹤",
    attr: "bing",
    sexType: "woman",
    star: 5,
  },
  Yelan: {
    key: "Yelan",
    name: "夜兰",
    attr: "shui",
    sexType: "woman",
    star: 5,
  },
  Xianyun: {
    key: "Xianyun",
    name: "闲云",
    attr: "feng",
    sexType: "woman",
    star: 5,
  },
  RaidenEi: {
    key: "RaidenEi",
    name: "雷电影",
    attr: "lei",
    sexType: "woman",
    star: 5,
  },
  Sara: {
    key: "Sara",
    name: "九条裟罗",
    attr: "lei",
    sexType: "woman",
    star: 4,
  },
  Miko: {
    key: "Miko",
    name: "八重神子",
    attr: "lei",
    sexType: "woman",
    star: 5,
  },
  Candace: {
    key: "Candace",
    name: "坎蒂丝",
    attr: "shui",
    sexType: "woman",
    star: 4,
  },
  Dehya: {
    key: "Dehya",
    name: "迪希雅",
    attr: "huo",
    sexType: "woman",
    star: 5,
  },
  Navia: {
    key: "Navia",
    name: "娜维娅",
    attr: "yan",
    sexType: "woman",
    star: 5,
  },
  Amber: { key: "Amber", name: "安柏", attr: "huo", sexType: "girl", star: 4 },
  Barbara: {
    key: "Barbara",
    name: "芭芭拉",
    attr: "shui",
    sexType: "girl",
    star: 4,
  },
  Noelle: {
    key: "Noelle",
    name: "诺艾尔",
    attr: "yan",
    sexType: "girl",
    star: 4,
  },
  Fischl: {
    key: "Fischl",
    name: "菲谢尔",
    attr: "lei",
    sexType: "girl",
    star: 4,
  },
  Sucrose: {
    key: "Sucrose",
    name: "砂糖",
    attr: "feng",
    sexType: "girl",
    star: 4,
  },
  Mona: { key: "Mona", name: "莫娜", attr: "shui", sexType: "girl", star: 5 },
  Keqing: {
    key: "Keqing",
    name: "刻晴",
    attr: "lei",
    sexType: "girl",
    star: 5,
  },
  Ganyu: { key: "Ganyu", name: "甘雨", attr: "bing", sexType: "girl", star: 5 },
  Hutao: { key: "Hutao", name: "胡桃", attr: "huo", sexType: "girl", star: 5 },
  Xiangling: {
    key: "Xiangling",
    name: "香菱",
    attr: "huo",
    sexType: "girl",
    star: 4,
  },
  Xinyan: {
    key: "Xinyan",
    name: "辛焱",
    attr: "huo",
    sexType: "girl",
    star: 4,
  },
  Yanfei: {
    key: "Yanfei",
    name: "烟绯",
    attr: "huo",
    sexType: "girl",
    star: 4,
  },
  Yunjin: {
    key: "Yunjin",
    name: "云堇",
    attr: "yan",
    sexType: "girl",
    star: 4,
  },
  Ayaka: {
    key: "Ayaka",
    name: "神里凌华",
    attr: "bing",
    sexType: "girl",
    star: 5,
  },
  Yoimiya: {
    key: "Yoimiya",
    name: "宵宫",
    attr: "huo",
    sexType: "girl",
    star: 5,
  },
  Kokomi: {
    key: "Kokomi",
    name: "珊瑚宫心海",
    attr: "shui",
    sexType: "girl",
    star: 5,
  },
  Shinobu: {
    key: "Shinobu",
    name: "久岐忍",
    attr: "lei",
    sexType: "girl",
    star: 4,
  },
  Kirara: {
    key: "Kirara",
    name: "绮良良",
    attr: "cao",
    sexType: "girl",
    star: 4,
  },
  Chiori: {
    key: "Chiori",
    name: "千织",
    attr: "yan",
    sexType: "girl",
    star: 5,
  },
  Collei: {
    key: "Collei",
    name: "科莱",
    attr: "cao",
    sexType: "girl",
    star: 4,
  },
  Nilou: { key: "Nilou", name: "妮露", attr: "shui", sexType: "girl", star: 5 },
  Layla: {
    key: "Layla",
    name: "莱依拉",
    attr: "bing",
    sexType: "girl",
    star: 4,
  },
  Faruzan: {
    key: "Faruzan",
    name: "珐露珊",
    attr: "feng",
    sexType: "girl",
    star: 4,
  },
  Lynette: {
    key: "Lynette",
    name: "琳妮特",
    attr: "feng",
    sexType: "girl",
    star: 4,
  },
  Furina: {
    key: "Furina",
    name: "芙宁娜",
    attr: "shui",
    sexType: "girl",
    star: 5,
  },
  Charlotte: {
    key: "Charlotte",
    name: "夏洛蒂",
    attr: "bing",
    sexType: "girl",
    star: 4,
  },
  Chevreuse: {
    key: "Chevreuse",
    name: "夏沃蕾",
    attr: "huo",
    sexType: "girl",
    star: 4,
  },
  Aloy: { key: "Aloy", name: "埃洛伊", attr: "bing", sexType: "girl", star: 5 },
  Lumine: { key: "Lumine", name: "莹", sexType: "girl", star: 5 },
  Klee: { key: "Klee", name: "可莉", attr: "huo", sexType: "loli", star: 5 },
  Diona: {
    key: "Diona",
    name: "迪奥娜",
    attr: "bing",
    sexType: "loli",
    star: 4,
  },
  Qiqi: { key: "Qiqi", name: "七七", attr: "bing", sexType: "loli", star: 5 },
  Yaoyao: {
    key: "Yaoyao",
    name: "瑶瑶",
    attr: "cao",
    sexType: "loli",
    star: 4,
  },
  Sayu: { key: "Sayu", name: "早柚", attr: "feng", sexType: "loli", star: 4 },
  Dori: { key: "Dori", name: "多莉", attr: "lei", sexType: "loli", star: 4 },
  Nahida: {
    key: "Nahida",
    name: "纳西妲",
    attr: "cao",
    sexType: "loli",
    star: 5,
  },
  // Paimon: { key: "Paimon", name: "派蒙", sexType: "loli", star: 5 },
  Aether: { key: "Aether", name: "空", sexType: "man", star: 5 },
  Mika: { key: "Mika", name: "米卡", attr: "bing", sexType: "man", star: 4 },
  Razor: { key: "Razor", name: "雷泽", attr: "lei", sexType: "man", star: 4 },
  Venti: { key: "Venti", name: "温蒂", attr: "feng", sexType: "man", star: 5 },
  Bennett: {
    key: "Bennett",
    name: "班尼特",
    attr: "huo",
    sexType: "man",
    star: 4,
  },
  Albedo: {
    key: "Albedo",
    name: "阿贝多",
    attr: "yan",
    sexType: "man",
    star: 5,
  },
  Gaming: { key: "Gaming", name: "嘉明", attr: "huo", sexType: "man", star: 4 },
  Xiao: { key: "Xiao", name: "魈", attr: "feng", sexType: "man", star: 5 },
  Xingqiu: {
    key: "Xingqiu",
    name: "行秋",
    attr: "shui",
    sexType: "man",
    star: 4,
  },
  Chongyun: {
    key: "Chongyun",
    name: "重云",
    attr: "bing",
    sexType: "man",
    star: 4,
  },
  Kazuha: {
    key: "Kazuha",
    name: "枫原万叶",
    attr: "feng",
    sexType: "man",
    star: 5,
  },
  Gorou: { key: "Gorou", name: "五郎", attr: "yan", sexType: "man", star: 4 },
  Heizou: {
    key: "Heizou",
    name: "鹿野院平藏",
    attr: "feng",
    sexType: "man",
    star: 4,
  },
  Tighnari: {
    key: "Tighnari",
    name: "缇纳里",
    attr: "cao",
    sexType: "man",
    star: 5,
  },
  Cyno: { key: "Cyno", name: "赛诺", attr: "lei", sexType: "man", star: 5 },
  Wanderer: {
    key: "Wanderer",
    name: "流浪者",
    attr: "feng",
    sexType: "man",
    star: 5,
  },
  Lyney: { key: "Lyney", name: "林尼", attr: "huo", sexType: "man", star: 5 },
  Freminet: {
    key: "Freminet",
    name: "菲米尼",
    attr: "bing",
    sexType: "man",
    star: 4,
  },
  Zhongli: {
    key: "Zhongli",
    name: "钟离",
    attr: "yan",
    sexType: "man",
    star: 5,
  },
  Baizhu: { key: "Baizhu", name: "白术", attr: "cao", sexType: "man", star: 5 },
  Kaeya: { key: "Kaeya", name: "凯亚", attr: "bing", sexType: "man", star: 4 },
  Diluc: { key: "Diluc", name: "迪卢克", attr: "huo", sexType: "man", star: 5 },
  Thoma: { key: "Thoma", name: "托马", attr: "huo", sexType: "man", star: 4 },
  Itto: { key: "Itto", name: "荒泷一斗", attr: "yan", sexType: "man", star: 5 },
  Ayato: {
    key: "Ayato",
    name: "神里绫人",
    attr: "shui",
    sexType: "man",
    star: 5,
  },
  Alhaitham: {
    key: "Alhaitham",
    name: "艾尔海森",
    attr: "cao",
    sexType: "man",
    star: 5,
  },
  Kaveh: { key: "Kaveh", name: "卡维", attr: "cao", sexType: "man", star: 4 },
  Tartaglia: {
    key: "Tartaglia",
    name: "达达利亚",
    attr: "shui",
    sexType: "man",
    star: 5,
  },
  Neuvillette: {
    key: "Neuvillette",
    name: "那维莱特",
    attr: "shui",
    sexType: "man",
    star: 5,
  },
  Wriothesley: {
    key: "Wriothesley",
    name: "莱欧斯利",
    attr: "bing",
    sexType: "man",
    star: 5,
  },
};
